### ISSUE TITLE
[Feature Request] Mode where layers don't bleed into each other

### ISSUE THREAD

**Issue by realisticdreamer114514** [Haoming02/sd-forge-couple#57]
Can you find a way for individual layer's tokens to be more cleanly cut from each other than the default so that objects from individual layers don't bleed into each other (something like what regional prompter's latent mode used to do until it sorta broke for me?) 

It could be useful for creative use of multiple views or even fusions. Let say I want to showcase Kitagawa Marin's multiple cosplays in layers from top to bottom, and I absolutely don't want 1 costume to disfigure another. Or I want to do a chimera without using any lora. Both cases I need layers that are consistent inside and sharply cut off outside.

**Comment by Haoming02** [comment]
That is probably not possible with this Extension. 

`Attention Couple`, afaik, only works with the conditioning *(**eg.** prompt)*. Therefore, think of it as a really advanced LLM: It can "prompt" for which objects go where, but it cannot separate regions at a pixel level.

There is a reason why this is usually faster than `Latent Couple`, due to having only one Latent tensor throughout the pipeline.
