### ISSUE TITLE
laggy performance

### ISSUE THREAD

**Issue by rktvr** [Haoming02/sd-forge-couple#65]
using 3.2.0 and reforge

i'm getting really awful performance when trying to draw a mask, is anyone else getting that?
it's hitting some cpu cores pretty hard for (no visible) reason: 
![image](https://github.com/user-attachments/assets/adaefca1-53ea-4c57-af43-e9e140536672)

it's dragging the overall performance of the ui down, typing anything into any box takes several seconds etc.
I believe this is an issue with gradio4, as the civitai plugin also has this performance issue: https://github.com/BlafKing/sd-civitai-browser-plus/pull/341

it's making the mask feature completely unusable which is a shame.

**Comment by rktvr** [comment]
alright, i think i've narrowed it down a bit.

while drawing the mask, if you go over the border while drawing it instantly kills performance

**Comment by Haoming02** [comment]
Well, as this seems to be a reForge-specific (?) issue, I probably cannot do much.

The Extension works fine on both Gradio 3 and Gradio 4 versions of Forge though.

**Comment by rktvr** [comment]
indeed! works far better on forge. is a shame because reforge is much faster, however the mask tools are also much nicer on forge.
closing this issue as it is a problem with reforge and not the plugin!

**Comment by Number6UK** [comment]
This might be related to the Gradio3 DPI bug
I don't have the issue number to hand right now, but it affects all the SD WebUIs that use Gradio 3.

If the page that has the canvas element you're drawing in is being scaled to more than 100% then something gets miscalculated for the canvas size and browser performance plumets to the point it can become unusuable.

I noticed it when trying to use inpaint sketching.

It definitely happens if your system's global DPI is > 100% and I've seen it reported that it also happens if your page zoom level is over 100%

Gradio have said they they will not fix the issue in Gradio 3.

You can test to see if this is the cause of your issue by doing both of the following:

1) Close the browser (not just the tab) which is running the WebUI

2) Set your OS global DPI scaling to 100% (note this will make everything extremely tiny on a high res high DPI monitor, but it's only temporary)

3) Open the browser that you're going to use for the WebUI

4) Go to the WebUI page and make sure that it's zoomed to 100% (e.g. on Firefox Windows it's Ctrl-0)

5) See if the problem has stopped occuring (e.g. no longer laggy, normal responsiveness)

If that's fixed the problem then it's the Gradio 3 DPI bug.
Once you've done all the above steps you can set your system DPI back to whatever it was before (e.g. 125%, 150%, etc.)

My workaround at the moment (on Windows 11, but there'll be an equivalent for the other OSs), which I'm still testing but seems to work so far, is to:

1) Always use a particular browser for WebUI stuff; in my case, Firefox Developer Edition.

2) Create a shortcut for the browser's .exe

3) Right cilck the shortcut > `Compatibility` tab > `Change high DPI settings` button

4) In Program DPI,  tick the box `Use this setting to fix scaling problems for this program instead of the ones in Settings`

5) In High DPI scaling override, tick the box `Override high DPI scaling behaviour`. In the `Scaling performed by:` dropdown, choose `System (Enhanced)`  (this might not be available on older versions of Windows - if not, try one of the other options; I haven't tested them myself yet)

6) Press OK to close the High DPI settings window,

7) Press OK to close the shortcut properties window.

8) Close any instance of the browser affected by the High DPI change - e.g. if you were setting the DPI settings on a shortcut to chrome.exe, close all instances of Chrome.

9) Start the browser **from the shortcut you set the properties on**

10) Open the WebUI in that browser and see if the bug still occurs


Hopefully it will help you. The main drawbacks to this workaround are having to use a different browser just for WebUI, the fonts being a tiny bit less pretty, and some odd mouseover issues where tooltips sometimes show up a large distance from the mouse cursor. I've not found anything that's actually broken by this method however and have been using it for over a week now sucessfully.

Hope it works for you too.
